### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by mohlsen** [mohlsen/check-engine#1]
name is not idea, having `.js` in package name is a bad practice.

**Comment by YashdalfTheGray** [comment]
How about `version-cheker`, `check-versions` or `check-env`?

**Comment by kwpeters** [comment]
I like "engine-check" or "check-engine". Then, our icon/logo could be a glowing check engine light!  What do you think @mohlsen and @yashdalfthegray?

**Comment by mohlsen** [comment]
Killer. 👍👍

**Comment by YashdalfTheGray** [comment]
Oh yeah, 💯
