### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mohlsen** [mohlsen/check-engine#28]
Confirm this runs on windows, and also add a windows validator

**Comment by YashdalfTheGray** [comment]
It works on Windows, I tested and also developed some of it on Windows. I'll add the windows validator.

**Comment by mohlsen** [comment]
Woot

**Comment by kwpeters** [comment]
Should we now avoid anything related to brew to preserve Windows operation?

**Comment by mohlsen** [comment]
No, I don't think so. If someone has a windows specific project that needs system validation, then the assumption would be thee would not have any brew packages in their engines. If they did have brew packages to validate, then I think it would be safe to assume they require OSX.

**Comment by mohlsen** [comment]
I guess the catch would be if someone had a cross platform project, and a dependency that needed validated was on both platforms, and happened to be installed via brew on OSX.

**Comment by mohlsen** [comment]
But in those cases, it might be installed in a way the validator could not use brew commands (like a git validator would). For both the brew checks now, since they are iOS development tests, I think we are ok.
