### ISSUE TITLE
add gulp validator

### ISSUE THREAD

**Issue by mohlsen** [mohlsen/check-engine#36]

**Comment by kwpeters** [comment]
I'm not sure this is validator is really necessary.  The preferred way of using Gulp is to install gulp as a local dependency.  gulp-cli should be installed globally, but its version is not really that important, because it simply runs the locally installed gulp version.

**Comment by mohlsen** [comment]
So would it just be better to check for the presence of gulp-cli?  If a project uses gulp, and they have it installed locally, but the CLI is not installed, they will not be able to run gulp from the command line.

**Comment by mohlsen** [comment]
Fixed with #47.  check for CLI version.
