### ISSUE TITLE
Add TypeScript typings?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mohlsen/check-engine#50]
It would be great if this shipped with TypeScript typings (or were even written in TypeScript!). That way we'd get better editor auto-completion in VS Code and/or when using TypeScript.

https://github.com/DefinitelyTyped/DefinitelyTyped/

I can send a PR with an index.d.ts unless directed otherwise. I'd be willing to convert to TS also.

**Comment by mohlsen** [comment]
Would for sure take a PR with Typings. Thanks!

As far as converting to TS, that would be great too, but would want to discuss the deployment options.  Questions:

- Would we want to add a build step that would be run just before an `npm publish` that would include the TS compile result?
- Would we just check in the compiled version into a `./bin` folder?
- Would we just have people who install this have a package.json npm postingall script to run the typescript compiler?

What is your preference?  What are you seeing these day for TS based node modules?

**Comment by JoshuaKGoldberg** [comment]
> Would we want to add a build step that would be run just before an npm publish that would include the TS compile result?

Typically yes.

> Would we just check in the compiled version into a ./bin folder?

Typically no. You would `.gitignore` (but not `.npmignore`) any `.js`/`.js.map` file generated by TypeScript.

> Would we just have people who install this have a package.json npm postingall script to run the typescript compiler?
> What is your preference? What are you seeing these day for TS based node modules?

These days, for projects that don't use big webpack setups, most of what I've seen is having `typescript` and `tslint` as `devDependency`s in package.json. People can use `tsc -w .` during development to have the incremental compiler run in watch mode (it's _fast_ as of the last version!). Builds then run `tsc -p .` and `tslint -f stylish -p tsconfig.json` in series. Releases run `tsc -p`.

As for how to convert to TypeScript, it's common to:
1. Rename all `.js` files to `.ts`
2. Add the above ignores & build & release steps
3. Fix any build errors
4. Be happy

**Comment by mohlsen** [comment]
cool.  So seems like `npm prepublish` is the way to do things these days.  We'd be cool with this approach and moving to TS.
