### ISSUE TITLE
Add option --force to prevent process exit

### ISSUE THREAD

**Issue by bastienmoulia** [mohlsen/check-engine#54]
All in the title

**Comment by mohlsen** [comment]
Are you talking about not ending the process when the check completes?  What would be the advantage of this?

**Comment by bastienmoulia** [comment]
In some case i want to display the engines version but don't care if they are not good. I don't want to block the full process in dev mode by example. But i do for production.

**Comment by mohlsen** [comment]
ah ok.  its not so much blocking process, but not returning an error code when the process exits (if using the CLI) or not rejecting the promise (if using it in code).

Which way are you using it?

**Comment by bastienmoulia** [comment]
Yes, I use it in the CLI, in the ‘postinstall’ script.

**Comment by mohlsen** [comment]
added `--ignore` option for this use case.
