### ISSUE TITLE
bug: version 1.12.0 doesn't seem to bring pnpm support

### ISSUE THREAD

**Issue by cguy** [mohlsen/check-engine#88]
Hi!

Thank you for your helpful library.

I have an issue with your last version which claims to support `pnpm`. Well, it doesn't, we I look into source code of your 1.12.0 tag, pnpm reference is missing: https://github.com/mohlsen/check-engine/blob/v1.12.0/lib/validatorRules.js

Could you please create a new release?

Best regards,

**Comment by mohlsen** [comment]
fixed in [v1.14.0](https://github.com/mohlsen/check-engine/releases/tag/v1.14.0)

sorry about that!
